/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.a04t.app;

import com.a04t.list.LinkedList;

import static com.a04t.utilities.StringUtils.join;
import static com.a04t.utilities.StringUtils.split;
import static com.a04t.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result) + " - App!");
    }
}
